version: "3.3"

services:
  rest-api:
    image: "node:20-alpine"
    user: "node"
    working_dir: /home/node/app
    container_name: "slo-rest-api"
    environment:
      - NODE_ENV=development
      - NODE_PORT=4500
      - NODE_BASE=/
      - NODE_ID_URL=/uuid/
      - NODE_SEARCH_URL=http://slo-search:3001
      - NODE_DATA_URL=http://localhost:4500/
      - NODE_SIMPLYSTORE_URL=http://curriculum-store:3000
    volumes:
      - ./curriculum-rest-api/:/home/node/app
    ports:
      - "4500:4500"
    depends_on:
      - curriculum-store
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        npm install
        npm start

  search-server:
    image: "node:20-alpine"
    user: "node"
    working_dir: /home/node/app
    container_name: "slo-search"
    environment:
      - NODE_ENV=development
      - NODE_PORT=3001
      - DATA_DIR=/home/node/app/curriculum
    volumes:
      - ./curriculum-search-server/:/home/node/app
      - ./curriculum-graphql-server/data/:/home/node/app/curriculum
    ports:
      - "3001:3001"
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        npm install
        npm start

  curriculum-store:
    image: "node:20-alpine"
    user: "node"
    working_dir: /home/node/app
    container_name: "curriculum-store"
    environment:
      - NODE_ENV=development
      - NODE_PORT=3000
      - DATA_DIR=/home/node/app/curriculum
    volumes:
      - ./curriculum-store/:/home/node/app
    ports:
      - "3000:3000"
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        npm install
        npm start

volumes:
  curriculum-rest-api:
  curriculum-search-server: