version: "3.3"

services:
  rest-api:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    container_name: "rest-api"
    environment:
      - NODE_ENV=development
    volumes:
      - ./curriculum-rest-api/:/home/node/app
    ports:
      - "4500:4500"
    depends_on:
      - graphql
    command: "npm start"

  graphql:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    container_name: "graphql"
    environment:
      - NODE_ENV=development
    volumes:
      - ./curriculum-graphql-server/:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"

volumes:
  curriculum-graphql-server:
  curriculum-rest-api: